# Generated by Django 4.1.3 on 2022-12-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseases',
            name='pub_date',
        ),
    ]
