# Generated by Django 4.1.3 on 2022-12-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_diseases_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseases',
            old_name='disease',
            new_name='name',
        ),
    ]
