# Generated by Django 4.1.3 on 2022-12-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_disease_diseases_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseases',
            name='description',
            field=models.TextField(default='TODO'),
        ),
    ]
