# Generated by Django 4.1.3 on 2022-12-17 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_diseases_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='diseases',
            new_name='disease',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='question',
            new_name='question_text',
        ),
    ]
